#!/usr/bin/env python3
"""Amalgamate a header and all its local includes into a single file."""

import re
import sys
from pathlib import Path

INCLUDE_RE = re.compile(r'^\s*#include\s+"([^"]+)"')
SYSTEM_INCLUDE_RE = re.compile(r'^\s*#include\s+<[^>]+>')
PRAGMA_ONCE_RE = re.compile(r'^\s*#pragma\s+once\s*$')

seen: set[Path] = set()
seen_system: set[str] = set()


def amalgamate(path: Path, root: Path) -> list[str]:
    path = path.resolve()
    if path in seen:
        return []
    seen.add(path)

    lines: list[str] = []
    lines.append(f"// ---- {path.relative_to(root)} ----\n")

    for line in path.read_text().splitlines(keepends=True):
        if PRAGMA_ONCE_RE.match(line):
            continue
        if SYSTEM_INCLUDE_RE.match(line):
            stripped = line.strip()
            if stripped in seen_system:
                continue
            seen_system.add(stripped)
        m = INCLUDE_RE.match(line)
        if m:
            # Try relative to the including file, then relative to root.
            candidate = (path.parent / m.group(1)).resolve()
            if not candidate.exists():
                candidate = (root / m.group(1)).resolve()
            if candidate.exists():
                lines.extend(amalgamate(candidate, root))
                continue
        lines.append(line if line.endswith('\n') else line + '\n')

    return lines


def main() -> None:
    if len(sys.argv) not in (3, 4):
        print(f"usage: {sys.argv[0]} <input.h> <output.h> [root-dir]", file=sys.stderr)
        sys.exit(1)

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    root = Path(sys.argv[3]).resolve() if len(sys.argv) == 4 else src.parent.resolve()

    header = "#pragma once\n// Single-header amalgamation — generated by scripts/amalgamate.py\n\n"
    body = "".join(amalgamate(src, root))
    dst.write_text(header + body)
    print(f"wrote {dst}")


if __name__ == "__main__":
    main()
